### ISSUE TITLE
Mover los archivos de diseño ajenos a Unity fuera del proyecto Map

### ISSUE THREAD

**Issue by daniapa** [jgirald/ES2015C#101]
Seria interesante para el final de este sprint 2 que los modelos que se suban dentro de la carpeta Map/Assets/Models solo contengan los archivos que son necesarios para el proyecto en Unity. Con lo que no haria falta poner los .blend y .psd, que hacen que el proyecto pese bastante.

Lo ideal creo yo y para que este todo dentro del github, seria crear una carpeta en la raíz del proyecto y adjuntar en esa carpeta todos esos archivos que no son "necesarios" para el funcionamiento del proyecto en Unity.

Por favor, comentad si estáis de acuerdo y a ver como lo hacemos.

**Comment by achafa** [comment]
De acuerdo, hemos quitado de la rama teamBsprint2 los ficheros con extensión .blend
Creamos una subrama de dev llamado teamBbuilding con los ficheros .blend

**Comment by daniapa** [comment]
Como que no se si todo el mundo habrá visto esta issue de los grupos A y B. Tenia pensado cuando pasemos del dev al master, crear una carpeta en la raíz igual que esta la de Documentacion que sea ModelosBlender y poner en esta con la misma estructura que ahora hay en Map/Assets/Models los modelos con todo completo y quitar de la carpeta del proyecto Unity los .blend y .psd.

Gracias igualmente.
