### ISSUE TITLE
Citizen Enemy AI decision making

### ISSUE THREAD

**Issue by zaiken** [jgirald/ES2015C#157]
Description.
EnemyAI decide to look for a tree, got to it and harvest some wood from a tree.

BRANCH link:
https://github.com/jgirald/ES2015C/tree/Issue157

Definition of DONE.
The citizen will walk around the map, searching for a tree. One found it, will harvest some wood and return to the  Citizen Center to add its resource to the wood global account.

Effort: About 2 hours

**Comment by Waltraud** [comment]
La lògica concreta de com una unitat civil recolectarà fusta d'un arbre la implementarà l'equip C... Tu hauria de decidir quan fa això la IA i cridar una funció tipus recolectar(unitat, arbre). No sé exactament com serà perquè la estem fent en aquest Sprint. Parla amb la Sara García per coordinarte!

**Comment by zaiken** [comment]
Efectivament, jo com a equip de IA faig el relacionat amb un non-human
Civil. Quan ho tingui, la part que ha de fer la Sara hauria de ser
practicament igual excepte que en comptes d'autoassignar-se on i quan
tallar fusta (per exemple) es farà mitjançant un click del ratoli.

2015-10-24 15:57 GMT+02:00 Waltraud <notifications@github.com>:

> La lògica concreta de com una unitat civil recolectarà fusta d'un arbre la
> implementarà l'equip C... Tu hauria de decidir quan fa això la IA i cridar
> una funció tipus recolectar(unitat, arbre). No sé exactament com serà
> perquè la estem fent en aquest Sprint. Parla amb la Sara García per
> coordinarte!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgirald/ES2015C/issues/157#issuecomment-150813835>.
>



--

**Comment by Waltraud** [comment]
Clar, però no s'ha de repetir el codi dos cops. Tu hauries de fer servir el que farà la Sara per implementar la teva estratègia de la IA. Els civils tindran els mateixos mètodes independentment del seu owner (jugador humà o ordinador).

**Comment by sseerr20** [comment]
Rubén,  la teva feina es saber quan i que han de recollir i com trobar el recurs

**Comment by zaiken** [comment]
Re-opened Issue with new DONE definition and description
