### ISSUE TITLE
Implement the second menu to choose the game options (e.g. map, civilization, etc.)

### ISSUE THREAD

**Issue by joanbm** [jgirald/ES2015C#165]
**Backlog item:** As a user, I want to select one civilization to play. [High priority]

**Estimated effort:** 3 hours

**Ending condition:** Clicking on the "New Game" option of the main menu will bring the user to a second menu which contains various toggles to choose the gameplay options. Those options will be, for the time being, the civilization to play as, and the map in which to play. A finish button will exist which will then launch the correct map. The implementation must make the chosen parameters available to the map scripts, but MUST NOT actually do the required logic (switch the civilization, etc.). This is deferred to a further issue.

**Comment by ftorraba7** [comment]
Tras la última clase de prácticas Jesús me comento que no era necesario hacer 3 campañas, que únicamente con 2 mapas era suficiente, que debía avanzar en otros temas, por lo que como en el Sprint 2 cree 3 mapas, en el menú únicamente habrá selección paras dos mapas, o en su defecto para 3 y con una desactivada ya que el 3 mapa no estara acabado(si finalmente el juego esta avanzado como para permitirme avanzarlo, así lo hare). Por tanto, las escenas correctas son "map" y "campaña1". (Se cambiaran los nombres si es necesario cuando se junte en dev para evitar conflictos)

**Comment by joanbm** [comment]
OK, de acuerdo, lo hago así entonces!

**Comment by joanbm** [comment]
Done and joined into the team branch. The menu offers the option to choose the campaign to play, not the civilization, because that is what is implemented ATM, so the ending condition had to be changed after further study.
