### ISSUE TITLE
Modelar Persian Town Center

### ISSUE THREAD

**Issue by achafa** [jgirald/ES2015C#372]
**Descripción:** Modelar Persian Town Center

**Estimación de esfuerzo por horas:** 3h

**Definición de DONE:**  Obtener una estuctura mateninendo un estilo similar a los otros edificions de la misma civilización de twon center y que se relacione al estilo persa

**Responsable:** Arnau Sánchez, TeamB

**Comment by howna13** [comment]
![tumblr_inline_nq2hogrkj51rnnq7p_500](https://cloud.githubusercontent.com/assets/5635059/11220907/7f72c314-8d62-11e5-8d37-ee72c661b3c4.gif)

**Comment by achafa** [comment]
![ptc_sintexturas](https://cloud.githubusercontent.com/assets/7187013/11320221/bc4ecd28-9091-11e5-8fa4-8a0dbbda4977.png)
