### ISSUE TITLE
Show an "in-construction" building while a building is being built

### ISSUE THREAD

**Issue by Waltraud** [jgirald/ES2015C#377]
Currently, when a unit is building something, the building looks the same as when it is completely built. We want to show a half-built building instead.

Product backlog item: 1 - As a player, I want to create buildings by collected resources, so that I can grow my civilization. All buildings are characterized by a construction time and a degree of preservation (similar to degree of life in units). [High priority]

Estimated effort: 8 hours

Ending condition: When a unit is selected, and then the "build x building" button is pressed, the unit will start building (as before). The building should appear half-built, and no building actions should be possible. When the health of the building is full, the building should appear as normal. If the health is later lowered (if the building is being attacked) its appearance should not change.

**Comment by colivaol8** [comment]
Ya tengo el edificio Hitties Town Center Semiderruido, le tengo que hacer lo de los prefabs? si es asi me puedes decir como era? Ya teneis la lista de los edficios que estan hechos/ que se haran para este sprint en la wiki para que podais preparar el script.
