### ISSUE TITLE
Integrate the enemy unit's civilization selection with the enemy unit's unit spawn

### ISSUE THREAD

**Issue by joanbm** [jgirald/ES2015C#445]
During the end of the 4th sprint, a mechanism was created to spawn the units created by the main player and the enemy team, according to the selection made in the menu. This was working on the branch of the team (team C) that developed this issue. During the merge, it was found that teamD created an alternative mechanism to spawn the enemy units since they needed this feature immediately in this branch. The code that spawned those units was deemed impossible to merge during the integration and therefore this feature was delayed until the next sprint.

The purpose of this issue is to research how to integrate both enemy civilizations spawn (either immediately if it is deemed logical that teamC can handle this problem, or by communicating the necessary steps to be taken to a member of teamD so they can handle this problem).

**Product backlog item:** As a user, I want to select one civilization to play. [High priority]

**Estimated effort:** 2h

**Ending condition:** A class must exist which allows to spawn the various units and buildings according to the civilization. Ideally, if the final integration can be done, all units and buildings initially created for the enemy player and spawned for the enemy must be of the civilization that was chosen in the menu when starting the game.

**Comment by ftorraba7** [comment]
Una pregunta Joan, 

He creado ya las referencias por Script para crear las unidades del Enemigo, me falta únicamente comprobarlo añadiendo la clase RTSObjectFactory/RTSObjectType, pero ¿como compruebas tú en Unity que es correcto? Es decir, cuando ejecutas el juego, se ejecuta la escena por decirlo de alguna forma, ¿Cómo puedo ejecutarlo en Unity para ver el inicio del juego desde el menú? Quiero decir, como se muestra en la Release.

**Comment by joanbm** [comment]
No se si entiendo bien lo que me comentas, imagino que te refieres a cómo ejecutar el juego desde el principio de forma que puedas elegir la civilización del enemigo y ver que funcione después del cambio?

En este caso hay básicamente 3 formas:
- (Peor forma) Una es compilar el release, para eso desde el editor de Unity, en la barra de menús, ve a File -> Build and Run, lo dejas todo igual y le das a "Build and Run", entonces esperas un buen rato que se compile y tendrás ya el .EXE que empezará desde el menú y podrás elegir la civilización.

- Otra es, en vez de abrir el map.unity, abre el menu.unity y ejecutas la escena desde el editor de Unity desde allí, así en vez de empezar directamente desde el escenario empezarás desde el menú y podrás elegir la civilización.

- (Más fácil) Desde la escena principal, ponte sobre el objeto "EnemyPlayer1" (o "EnemyPlayer2") que está dentro de "EnemyTeam", entonces en la barra de propiedades de la derecha verás que hay una propiedad que pone "Civilization", desde allí puedes cambiar la civilización por defecto sin pasar por el menú.

**Comment by joanbm** [comment]
This issue has been merged to the team¡'s branch.
