### ISSUE TITLE
More and better messages to show information to the player

### ISSUE THREAD

**Issue by daniapa** [jgirald/ES2015C#554]
<b>Description :</b> Show more messages to info to the player about the different thinks that happen during the game. Make that the old messages dessapear in certain time.

<b>Estimated effort :</b> 3 hours

<b>Product backlog item :</b> As a player, I want to see the features of my units/buildings selecting them with clicks. [High Priority]

<b>Ending condition :</b> Messages now dissapear after certain time. More message info about different actions of the game.

**Comment by joanbm** [comment]
One place where the messages can be improved would be when attempting to create a building whose prefab hasn't been created yet. Currently only a message is written on the (Unity) log and no feedback is given on the screen.
