### ISSUE TITLE
Create the Hittites tower

### ISSUE THREAD

**Issue by achafa** [jgirald/ES2015C#66]
As a player,  I want to create defense buildings, so that I can defend from attacks of my enemies. To make a defense could be done on diferent angle, I need a defense building, called tower.

Ending condition: Ending the structure

Priority: Medium

**Comment by sgalinma** [comment]
![hittites_tower](https://cloud.githubusercontent.com/assets/10981030/10560526/c9e194a6-750d-11e5-80da-18c40b2e062f.png)
