### ISSUE TITLE
Create the Yamato half-demolished wall 

### ISSUE THREAD

**Issue by achafa** [jgirald/ES2015C#71]
As a player, I want to create defense buildings, so that I can defend from attacks of my enemies. I want a wall. Like reality, I want to know if my defense is nearly to desapear because of attack's enemies so I could decide to rebuild it or not.

Ending condition: Ending the structure

Priority: Medium

**Comment by sgalinma** [comment]
![yamato_wall_semi](https://cloud.githubusercontent.com/assets/10981030/10560547/aee6d5fc-750e-11e5-9a20-365b4a9e1894.png)
