### ISSUE TITLE
Create the Yamato half-demolished tower

### ISSUE THREAD

**Issue by achafa** [jgirald/ES2015C#72]
As a player, I want to create defense buildings, so that I can defend from attacks of my enemies. As a player, I want to create defense buildings, so that I can defend from attacks of my enemies. Like reality, I want to know if my defense is nearly to desapear because of attack's enemies so I could decide to rebuild it or not. 
Ending condition: Ending the structure of half-demolished builfing

Priority: Medium

**Comment by sgalinma** [comment]
![yamato_tower_semi](https://cloud.githubusercontent.com/assets/10981030/10560551/b9c8ded4-750e-11e5-88e1-80efba780844.png)
