### ISSUE TITLE
actualitzar prefabs todos los prefabs creados por mi

### ISSUE THREAD

**Issue by achafa** [jgirald/ES2015C#776]
**Descripción:** Comprobar todos los prefabs en unity creados por mi. Volver a crear-lossi hace falta
Prefabs a revisar: 
 * Goldmine :+1:
 * Yamato_TownCenter  :+1:
 * Yamato_TownCenter_Semidemolished :+1:
 * Yamato_TownCenter_onConstruction  :red_circle: :+1:
 * Sumerian_TownCenter  :+1:
 * Sumerian_TownCenter_Semidemolished  :+1:
 * Sumerian_TownCenter_onConstruction :+1:
 * Sumerian_Academy_Semidemolished  :+1:
 * Persian_TownCenter :red_circle:  :+1:
 * Persian_TownCenter_Semidemolished :red_circle:  :+1:
 * Persian_TownCenter_onConstruction :red_circle:  :+1:
 * Persian_Wall  :+1:
 * Persian_Wall_onConstruction  :red_circle:  :+1:
 * Persian_Wall_Semidemolished  :+1: 
 * Persian_WallEntrance  :+1:
 * Persian_WallEntrance_Semidemolished :+1:
 * Persian_WallEntrance_onConstruction   :red_circle:  :+1:
 * Persian_WallTower :+1:
 * Persian_WallTower_Semidemolished :+1:
 * Persian_WallTower_onConstruction :+1:

Por cada prefab que falle, se creará rama del estilo: issue#776_Iniciales

**Estimación de esfuerzo por horas:** 1h

**Definición de DONE:** Los nombres tienen que ser los mismos que marca la wiki y se tienen que ver en el mapa con el tamaño adecuado

**Responsable:** Arnau Sánchez, TeamB

**Comment by achafa** [comment]
Prefab Goldmine :+1:

**Comment by achafa** [comment]
**Yamato_TownCenter**  :+1:

**Comment by achafa** [comment]
* Yamato_TownCenter_Semidemolished :red_circle:

**Comment by achafa** [comment]
* Yamato_TownCenter_onConstruction  :red_circle:

**Comment by achafa** [comment]
**Sumerian_TownCenter**  :+1:
![captura de 2015-12-08 09 39 06](https://cloud.githubusercontent.com/assets/7187013/11651247/a2e03fe2-9d8f-11e5-8351-e371eb18ffae.png)

**Comment by achafa** [comment]
* Sumerian_TownCenter_onConstruction :+1:

**Comment by achafa** [comment]
**Sumerian_TownCenter_onConstruction**
![captura de 2015-12-08 09 41 25](https://cloud.githubusercontent.com/assets/7187013/11651278/efc022c8-9d8f-11e5-84ad-e06ffd4dbfc0.png)
 :+1:

**Comment by achafa** [comment]
* Sumerian_Academy_Semidemolished  :+1: (obsercaciones: Fatla bola y está comprobado en local)
![captura de 2015-12-08 09 47 36](https://cloud.githubusercontent.com/assets/7187013/11651404/bc8bd9aa-9d90-11e5-84d0-707b55f84a40.png)

**Comment by achafa** [comment]
Persian_Wall  :+1:

**Comment by achafa** [comment]
* Persian_Wall_onConstruction  :red_circle: (observacions no tiene la misma anchura que Persian Wall)

**Comment by achafa** [comment]
**Persian_Wall_Semidemolished**  :+1: (obsercaciones: Fatla bola y está comprobado en local)
![captura de 2015-12-08 10 31 34](https://cloud.githubusercontent.com/assets/7187013/11652227/df2a9d7e-9d96-11e5-88f6-5bf903f01dae.png)

**Comment by achafa** [comment]
**Persian_WallEntrance**
![captura de 2015-12-08 10 33 41](https://cloud.githubusercontent.com/assets/7187013/11652302/364c6cfe-9d97-11e5-9d7f-4c1d22c80f23.png)
  :+1:

**Comment by achafa** [comment]
**Persian_WallEntrance_Semidemolished** :+1:  (obsercaciones: Fatla bola y está comprobado en local)
![captura de 2015-12-08 10 37 14](https://cloud.githubusercontent.com/assets/7187013/11652373/b0946552-9d97-11e5-9f34-1a07a87e39d8.png)

**Comment by achafa** [comment]
**Persian_WallEntrance_onConstruction**   :red_circle: (observacions no tiene la misma anchura que Persian WallEntrance)

**Comment by achafa** [comment]
* Persian_WallTower :+1:
![captura de 2015-12-08 10 55 43](https://cloud.githubusercontent.com/assets/7187013/11652839/3fd04630-9d9a-11e5-9f0b-40f52b88a379.png)

**Comment by achafa** [comment]
** Persian_WallTower_Semidemolished**  :+1: (observació: s'ha de pujar i no té la bola)
** Persian_WallTower_onConstruction** :+1:(observació: s'ha de pujar)
![captura de 2015-12-08 10 59 10](https://cloud.githubusercontent.com/assets/7187013/11652906/bc62b7dc-9d9a-11e5-9f52-a3155424e63d.png)

**Comment by achafa** [comment]
**Persian_TownCenter** :red_circle:
**Persian_TownCenter_Semidemolished** :red_circle:
**Persian_TownCenter_onConstruction** :red_circle:

**Comment by ftorraba7** [comment]
Cuando se añadan al dev principal todos los edificios y personajes, me encargaré yo de que se añadan las bolas dependiendo de la civilización que corresponda.

**Comment by ftorraba7** [comment]
Aseguraos también de que la orientación de los edificios semidemolished, onconstruction están acorde con el edificio principal, sino al pasar de un estado a otro la orientación del edificio en el juego cambiará.

**Comment by achafa** [comment]
Los edificios en principio estan acordes en cuanto a tamaño y orientación entre sus estados.
