### ISSUE TITLE
Tutorial de Git

### ISSUE THREAD

**Issue by achafa** [jgirald/ES2015C#78]

**Comment by zaiken** [comment]
Manual GitHub

Benvinguts al meravellós mon de GitHub. Aquest manual es tracta d’un petit HowTo on s’explica de forma ràpida com utilitzar l'eina GitHub des de la consola.

INTRODUCCIÓ

El primer que farem serà anar a la pàgina web de GitHub (https://github.com/) obrir-nos un compte, logar-nos, afegir un Repositori i descarregar , instal·lar l’eina git per poder accedir a les comandes que gestionen aquest util.lísim gestor de repositoris.

COMANDES BÀSIQUES

Una vegada tenim el git instal·lat, obrim una consola (Inici-Executar-“cmd.exe”) des d’on controlarem tots els nostres repositoris.

Clonar un repositori (clone)
========

En primer lloc anem a la carpeta on volem descarregar el projecte. Per exemple, si el volem a “C:\GitHub” escriurem `cd /C/GitHub`.

A continuació clonem el projecte:

 git clone https://github.com/jgirald/ES2015C

amb el que tindríem el projecte a `C:\GitHub\ES2015C`

Les comandes explicades a continuació se suposa que son executades des de dins d'aquest directori.

Moure's a la branca des d’on volem treballar (checkout)
========

Quan clonem el projecte estarem a la branca `master`. Això es pot comprobar fàcilment amb la comanda 

git branch

La branca en la que actualment estem treballant tindrà un * davant.

A més, si estem fent servir Git Bash (windows), la branca apareixerà al final de la ruta actual abans de cada input.

Supossem que som del subgrup 'D' dins el nostre grup de pràctiques de l’assignatura i volem anar a la branca corresponent al nostre subgrup (suposem que ja està creada, sinó més abaix s'explica com). 
Aquesta branca rep el nom de TeamD(IA+MAP)

Simplement farem: 

git checkout TeamD(IA+MAP)

Podem canviar  TeamD(IA+MAP)   pel nom de qualsevol branca, les quals poden ser consultades amb:

git branch -a

*Nota:* Afegint -a a la comanda, aquesta retorna les branques locals (descarregades) i les remotes. Independentment de si es local o remota (excepte HEAD), podem fer un checkout a aquesta utilitzant solament la última part.

Per exemple, si veiem remotes/origin/gh-pages, podem fer: 

git checkout gh-pages 

per anar a aquesta branca.

Crear una nova branca
========

Normalment, quan treballem amb una issue en concret, voldrem crear una nova branca per aquesta. El motiu principal per crear una branca nova i no treballar directament a dev_d és, simplement, per evitar conflictes amb altres commits (que ja gestionarem en la integració/merge).

Dit això, si som del grup "D" i volem treballar en una issue referent a "IA de l’enemic", podríem per exemple crear una nova branca anomenada 

dev_d-enemy_ai

Hi ha moltes formes de fer-ho, però la més sencilla crearà la branca **a partir de la actual** i ens hi mourà. Per tant, sent el grup "D" farem:

git checkout dev_d  # Ens movem a "dev_d"
git checkout -b dev_d-enemy_ai  # Branch creada i ja hi som dins

El primer cop que intentem fer un push amb un branca nova, no podrem fer simplement git push, doncs remotament la branca dev_d-enemy_ai encara no existeix. Per tant, el que farem serà un push especificant destí i branca:

git push origin dev_d-enemy_ai

D’ara en endavant ja podrem fer simplement git push.

Nota: Per fer el primer push, que crea la branch remotament, no és necessari afegir nou codi ni editar res. Podem fer el push immediatament després del checkout

Nota2: Realment no és necessari enviar la branca remotament, sempre es pot treballar en local, fer un merge (com més endavant veurem) i pujar directament la branca sobre la que hem fet el merge.


Afegir arxius i fer un commit (add)
========

Supossem que estem al directori principal i volem fer un commit de tots els arxius modificats. Simplement farem:

git add .
git commit

Si solament volguéssim, per exemple, fer un commit de la carpeta Assets, faríem: 

git add Assets/

Ara tenim el commit fet, però solament en local, cal enviar-l'ho a Github:

git push

No és necessari fer un push per cada commit, automàticament enviarà tots els commits que tinguem en local, no solament l'últim.

Situació especial: He borrat un arxiu però al fer el commit, no es reflecteix
========

Quan fem canvis i els afegim per fer un commit, fent servir la comanda git add .
(on `.` es un directori, en aquest cas, l'actual).

Ara bé, aquesta comanda solament té en compte els arxius modificats, però no els borrats ni els moguts. Si volem que també els tingui en compte farem servir.

git add . -A


I el següent commit ja tindrà en compte tals arxius borrats i moguts.

Situació especial: He codificat en una branca que no tocava
==========
Si encara no has fet commit, tranquil, no passa res. Simplement fes un checkout a la branca on vulguis fer el commit i ja està. No perdràs cap canvi, així que no et preocupis.

Si ja has fet el commit, tot i que hi ha mètodes per arreglar-ho, són perillosos i poden reescriure l'arbre de referències del repositori, i per tant no les explicarem.

Donat aquest cas, pots si vols modificar el missatge del commit per esclarir que realment no hauria d'anar a la branca aquesta. Pots editar el missatge de l'últim commit (si no has fet push encara) amb:

git commit --amend

Si ja has fet el commit, o push, i encara vols treballar a la teva branca, fes un merge cap aquesta.

Integrar canvis entre branques (merge)
========

Supossem que ja hem fet els canvis que volíem en al branca `devel_d-unit_api` i que els volem integrar a la branca de treball del nostre grup. Se suposa que prèviament ja hem fet commits en aquesta branca. Farem:

git checkout dev_d
git merge dev_d-enemy_ai

Si tot va bé ja estarem i podràs saltar la secció següent.

Arreglant conflictes d'un merge
========

Del contrari tindrem conflictes a resoldre. Per arreglar-ho ens dirigirem als arxius que ens indica aquesta última comanda i buscarem blocs semblants a:

<<<<<<< HEAD
    codi_1
=======
    codi_2
>>>>>>> branch-a


Això indica que allí on nosaltres vam escriure un cert codi, algú altre també hi va escriure alguna altre cosa. Com sabem si cal mantenir `codi_1`, `codi_2` o ambdós?

No hi ha cap norma ni regla general, la única forma és mirar els commits indicats en aquetes línies:
Per exemple, HEAD indica l'últim commit en la branca dev_d (sobre on hem fet merge)
Però també podria haver-hi un hash d'un commit, tipus dff804cf0c3af9d353d919ea1f2528b472748303. En aquest cas, podem veure el commit i els canvis que va fer des de: https://github.com/jgirald/ES2015C/commit/HASH, o sigui, https://github.com/jgirald/ES2015A/commit/dff804cf0c3af9d353d919ea1f2528b472748303

Observant els canvis en aquests commits i els nostres propis haurem de decidir que borrar i/o editar. Evidenment cal borrar les línies <<<<... =====... >>>>>...

Un cop arreglats els conflictes farem:
git add .
git commit


Deixarem el missatge per defecte i acceptarem. Merge fet.


Integrar solament un commit (cherry-pick)
=======

Imaginem que estem treballant sobre dev_d-minimap pero necessitem un commit que s'ha fet en devel_c-enemy_api. Ara bé, un merge complet de les dues branques podría introduir masses conflictes.

El que farem s'anomena cherry-pick, és a dir, integrar un commit d'una altre branca en la nostra. Imaginem que el commit que necessitem té per hash dff806cf0c3af9d353d919ea1f2528b472748303. Si no el sabem, el podem consultar o desde github, apareix en la URL quan veiem el commit, o amb la comanda 

git log

i buscant el commit.

Un cop tenim l'hash i estem en la branca a on volem integrar el commit, farem:

git cherry-pick dff804cf0c3af9d353d919ea1f2528b472748303


Com en els merge, això pot anar perfectament bé o produir conflictes. Per resoldre els possibles conflictes ho farem de la mateixa forma que amb un `merge`, com s'explica a l'anterior apartat.


Borrar un branca
================

Ara que ja hem acabat de fer la API de les unitats volem borrar aquesta branca, dev_d-enemy_ai, perque ja no ens serveix i solament molesta.

Farem:

git branch -d dev_d-enemy_ai
Si a més a més vam fer un (o més) `push` d'aquesta branca, caldrà borrar remotament:

git push origin :dev_d-enemy_ai

There is no tracking information for the current branch.
=============
És possible que en clients git moderns es perdi, sobretot al fer pulls quan hi ha noves branques, la informació d'on s'ha de pujar una branca.

Com està comentat més adalt, una cosa es la branca local dev_d-enemy_ai i l'altre la remota remotes/origin/devel_d-unit_api. Normalment ambdues es corresponen en nom, en aquest cas dev_d-enemy_ai, però podrieu triar que no fos així.

En qualsevol cas, si no sabeu el nom de la branca remota, ho podeu consultar amb git branch -a

Com diu el missatge d'error, el problema es que git no sap a quina branca remota associar la branca local. En aquest cas, com que sabem que els noms es corresponen, simplement farem:

git branch --set-upstream-to=origin/dev_d-enemy_ai dev_d-enemy_ai

I problema solucionat. 
Fixa't que s'ha omés la part de remotes/, doncs ja ho té en compte automàticament

Alternativament, sempre podem fer un `pull` indicant origen i branca:

git pull origin dev_d-enemy_ai

**Comment by achafa** [comment]
Com s'actualitza un branca abans de començar?
