### ISSUE TITLE
Animación Samurai Yamato

### ISSUE THREAD

**Issue by perezdenavarro** [jgirald/ES2015C#85]
Creación de esqueleto para el samurai. Creamos nuevo esqueleto para eliminar posibles errores con el anterior diseño.
![yamatosamurai](https://cloud.githubusercontent.com/assets/6683864/10441578/edbc49fa-714a-11e5-8176-7d714abd8211.jpg)

**Comment by perezdenavarro** [comment]
Animación "Walk" terminada
https://youtu.be/cnJE8NHS9LI

**Comment by perezdenavarro** [comment]
Animación "Waiting" terminada
https://youtu.be/nItJ5dGXhXM

**Comment by perezdenavarro** [comment]
Animación "Run" terminada
https://youtu.be/vHig5lkxCCI

**Comment by perezdenavarro** [comment]
Animación "Dead" terminada
https://youtu.be/o1c7VmllRrU

**Comment by perezdenavarro** [comment]
Animación "Attack" terminada
https://youtu.be/UQYEHNDO_Ps

**Comment by howna13** [comment]
<a href="http://www.youtube.com/watch?feature=player_embedded&v=UQYEHNDO_Ps" target="_blank"><img src="http://img.youtube.com/vi/UQYEHNDO_Ps/0.jpg" width="240" height="180" /></a>
